version: '3'

services:
  OnePiecePostgres: 
    image: postgres:15.1
    container_name: onepiece_services
    environment:
      POSTGRES_DB: onepiece_services
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgAdmin:
    image: dpage/pgadmin4:6.17
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sistemas@itses.edu.mx
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "9090:80"
    depends_on:
      - OnePiecePostgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
